import BlogPost from "@components/BlogPost";
import Blog from "@models/Blog";
import connectDB from "@utils/connectDB";
import { ParseArrayMongoDocument } from "@utils/ParseMongoDocument";
import Head from "next/head";

export default (props) => {
  return (
    <div>
      <Head>
        <title>Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {props.error ? (
        <h1>something went wrong</h1>
      ) : (
        props.data.map((post) => <BlogPost key={post._id} data={post} />)
      )}
    </div>
  );
};

export const getServerSideProps = async () => {
  try {
    await connectDB();
    const response = await Blog.find();
    return {
      props: {
        data: ParseArrayMongoDocument(response),
        error: false,
      },
    };
  } catch (error) {
    console.log(error);
    return {
      props: {
        error: error.message,
      },
    };
  }
};
