import axios from "axios";
import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";
import styles from "../styles/Home.module.css";
export default () => {
  return (
    <div>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>nive</h1>
    </div>
  );
};

export const getStaticProps = async () => {
  try {
    const res = await axios.get("/api/blog");
    console.log(res);
    return {
      props: {
        data: res,
        response: true,
      },
    };
  } catch (err) {
    console.log(err);
    return {
      props: {
        data: err,
        response: false,
      },
    };
  }
};
