import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default ({ categories }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          <img />
          <a href="/">Home</a>
          <a href="/events">Events</a>
          <a href="/aboutus">About Us</a>
        </nav>
      </header>
      <main className={styles.main}>
        {categories.map((category) => (
          <a href={`/events/${category.id}`} key={category.id}>
            <Image src={category.image} width={200} height={150} />
            <h2>{category.title}</h2>
            <p>{category.description}</p>
          </a>
        ))}
      </main>
    </div>
  );
};

export const getServerSideProps = async () => {
  const data = await import("../data/data.json");
  return {
    props: {
      categories: data.events_categories,
    },
  };
};
